import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 * @author Wilberth Antonio López Aguilar
 */
public class VentanaPuntuacion extends JDialog {

    javax.swing.table.DefaultTableModel modelo;

    public VentanaPuntuacion(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarModelo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblTitulo = new javax.swing.JLabel("Puntuaciones");
        tabla = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton("Aceptar");
        btnLimpiar = new javax.swing.JButton("Limpiar");

        setTitle("Gato y Ratón");
        setSize(getPreferredSize());
        setLocationRelativeTo(getParent());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
        c.anchor = java.awt.GridBagConstraints.CENTER;
        c.fill = java.awt.GridBagConstraints.BOTH;
        c.insets.set(5, 5, 5, 5);
        setLayout(layout);

        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitulo.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 20));
        c.gridx = 2;
        c.gridy = 0;
        add(lblTitulo, c);

        c.gridx = 2;
        c.gridy = 1;
        tabla.getTableHeader().setVisible(true);
        tabla.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        ;
        tabla.setShowGrid(true);
        add(new javax.swing.JScrollPane(tabla), c);

        c.fill = java.awt.GridBagConstraints.NONE;
        c.gridx = 1;
        c.gridy = 3;
        btnLimpiar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, c);

        c.fill = java.awt.GridBagConstraints.NONE;
        c.gridx = 3;
        c.gridy = 3;
        btnAceptar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, c);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnLimpiarActionPerformed(ActionEvent evt) {
        limpiarModelo();
        cargarModelo();
    }

    protected void btnAceptarActionPerformed(ActionEvent evt) {
        dispose(); // Salir de la ventana.
    }

    /**
     * Carga todas las puntuaciones desde un archivo y las muestra en una tabla.
     */
    private void cargarModelo() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Jugador");
        modelo.addColumn("Fecha y Hora");
        modelo.addColumn("Puntos");
        tabla.setModel(modelo);

        ArrayList<Puntuacion> puntuaciones = null;

        try {
            puntuaciones = new Archivo().cargarPuntuaciones();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        lblTitulo.setText("Puntuaciones");

        if (puntuaciones != null) {
            for (Puntuacion puntuacion : puntuaciones) {
                modelo.addRow(puntuacion.toArray());

            }
        }
        repaint();
    }

    /**
     * Elimina todas las puntuaciones de la tabla y del archivo.
     */
    private void limpiarModelo() {
        try {
            // Sobreescribe el archivo con un ArrayList vacío.
            new Archivo().guardarPuntuaciones(new ArrayList<Puntuacion>());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntuacion.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntuacion.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntuacion.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntuacion.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPuntuacion dialog = new VentanaPuntuacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(800, 600);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
