import java.awt.Dimension;
import java.awt.event.ActionEvent;

import javax.swing.WindowConstants;

/**
 * @author Wilberth Antonio López Aguilar
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private String jugadorX;
    private String jugadorO;

    /**
     * Creates a new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        super();
        initComponents();
        // jugadorX = "Jugador X";
        // jugadorO = "Jugador O";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblTitulo = new javax.swing.JLabel("Menú");
        btnJugar = new javax.swing.JButton("Fácil");
        btnDificil = new javax.swing.JButton("Difícil");
        btnMuyDificil = new javax.swing.JButton("Muy Difícil");
        btnJugadores = new javax.swing.JButton("Jugadores");
        btnPuntuaciones = new javax.swing.JButton("Puntuaciones");
        btnSalir = new javax.swing.JButton("Salir");
        panelMenu = new javax.swing.JPanel();

        setTitle("Gato y Ratón");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(getPreferredSize());
        setLocationRelativeTo(null);

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
        c.fill = java.awt.GridBagConstraints.BOTH;
        c.anchor = java.awt.GridBagConstraints.CENTER;
        c.insets.set(5, 5, 5, 5);
        panelMenu.setLayout(layout);

        c.gridx = 1;
        c.gridy = 0;
        lblTitulo.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 25));
        panelMenu.add(lblTitulo, c);

        c.fill = java.awt.GridBagConstraints.NONE;

        c.ipadx = 80;
        c.gridx = 1;
        c.gridy = 1;
        btnJugar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarGatoActionPerformed(evt);
            }
        });
        panelMenu.add(btnJugar, c);

        c.ipadx = 74;
        c.gridx = 1;
        c.gridy = 2;
        btnDificil.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificultadActionPerformed(evt);
            }
        });
        panelMenu.add(btnDificil, c);

        c.ipadx = 40;
        c.gridx = 1;
        c.gridy = 3;
        btnMuyDificil.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnMuyDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuyDificultadActionPerformed(evt);
            }
        });
        panelMenu.add(btnMuyDificil, c);

        c.ipadx = 38;
        c.gridx = 1;
        c.gridy = 4;
        btnJugadores.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadoresActionPerformed(evt);
            }
        });
        panelMenu.add(btnJugadores, c);

        c.gridx = 1;
        c.gridy = 5;
        c.ipadx = 16;
        btnPuntuaciones.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnPuntuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntuacionesActionPerformed(evt);
            }
        });
        panelMenu.add(btnPuntuaciones, c);

        c.ipadx = 80;
        c.gridx = 1;
        c.gridy = 6;
        btnSalir.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelMenu.add(btnSalir, c);

        add(panelMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnJugarGatoActionPerformed(ActionEvent evt) {
        new VentanaGato(this, true, jugadorX, jugadorO, 3).setVisible(true);
    }

    protected void btnDificultadActionPerformed(ActionEvent evt) {
        new VentanaGato(this, true, jugadorX, jugadorO, 5).setVisible(true);
    }

    protected void btnMuyDificultadActionPerformed(ActionEvent evt) {
        new VentanaGato(this, true, jugadorX, jugadorO, 7).setVisible(true);
    }

    protected void btnJugadoresActionPerformed(ActionEvent evt) {
        VentanaJugadores ventana = new VentanaJugadores(this, true);
        ventana.setVisible(true);
        jugadorX = ventana.getJugadorX();
        jugadorO = ventana.getJugadorO();

    }

    protected void btnSalirActionPerformed(ActionEvent evt) {
        System.exit(0); // Salir del programa.
    }

    protected void btnPuntuacionesActionPerformed(ActionEvent evt) {
        new VentanaPuntuacion(this, true).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws Exception {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (info.getName().equals("Nimbus")) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        }

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaPrincipal().setVisible(true);
        });
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(800, 600);
    }

    // Variables declaration - do not modify
    // GEN-BEGIN:variables
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnMuyDificil;
    private javax.swing.JButton btnJugadores;
    private javax.swing.JButton btnPuntuaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

}
