import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;

import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 * @author Wilberth Antonio López Aguilar
 */
public class VentanaJugadores extends javax.swing.JDialog {

    private String jugadorX;
    private String jugadorO;

    public VentanaJugadores(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblTitulo = new javax.swing.JLabel("Jugadores");
        lblJugadorX = new javax.swing.JLabel("Jugador X");
        lblJugadorO = new javax.swing.JLabel("Jugador O");
        txtJugadorX = new javax.swing.JTextField(20);
        txtJugadorO = new javax.swing.JTextField(20);
        btnAceptar = new javax.swing.JButton("Aceptar");
        panel = new javax.swing.JPanel();

        setTitle("Gato y Ratón");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(getPreferredSize());
        setLocationRelativeTo(null);

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
        c.fill = java.awt.GridBagConstraints.BOTH;
        c.anchor = java.awt.GridBagConstraints.CENTER;
        c.insets.set(5, 5, 5, 5);
        panel.setLayout(layout);

        c.gridx = 2;
        c.gridy = 0;
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitulo.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 25));
        panel.add(lblTitulo, c);

        c.fill = java.awt.GridBagConstraints.NONE;

        c.gridx = 1;
        c.gridy = 1;
        lblJugadorX.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        lblJugadorX.setIcon(new javax.swing.ImageIcon(
                new javax.swing.ImageIcon("res/gato.png").getImage().getScaledInstance(48, 48, Image.SCALE_DEFAULT)));
        panel.add(lblJugadorX, c);

        c.gridx = 2;
        c.gridy = 1;
        txtJugadorX.setText("X");
        panel.add(txtJugadorX, c);

        c.gridx = 1;
        c.gridy = 2;
        lblJugadorO.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        lblJugadorO.setIcon(new javax.swing.ImageIcon(
                new javax.swing.ImageIcon("res/raton.png").getImage().getScaledInstance(48, 48, Image.SCALE_DEFAULT)));
        panel.add(lblJugadorO, c);

        c.gridx = 2;
        c.gridy = 2;
        txtJugadorO.setText("O");
        panel.add(txtJugadorO, c);

        c.gridx = 3;
        c.gridy = 3;
        btnAceptar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarGatoActionPerformed(evt);
            }
        });
        panel.add(btnAceptar, c);

        add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnAceptarGatoActionPerformed(ActionEvent evt) {
        jugadorX = txtJugadorX.getText();
        jugadorO = txtJugadorO.getText();
        dispose(); // Salir de la ventana.
    }

    /**
     * Devuelve el alias del jugadorX (Gato).
     * 
     * @return String
     */
    public String getJugadorX() {
        return jugadorX;
    }

    /**
     * Devuelve el alias del jugadorO (Ratón).
     * 
     * @return String
     */
    public String getJugadorO() {
        return jugadorO;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJugadores.class

                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaJugadores dialog = new VentanaJugadores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(800, 600);
    }

    // Variables declaration - do not modify
    // GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblJugadorX;
    private javax.swing.JLabel lblJugadorO;
    private javax.swing.JTextField txtJugadorX;
    private javax.swing.JTextField txtJugadorO;

    // End of variables declaration//GEN-END:variables

}
